<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 True Action Network (http://www.trueaction.com)
 */
?>

<h4 id="heading_<?php echo $this->getHtmlId() ?>"><?php echo $this->getElementLabel() ?></h4>
<div id="system-fieldset-sub-head-comment"><?php echo $this->getElementComment() ?></div>
<div>
	<button  class="scalable add" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span><?php echo $this->escapeHtml($this->getButtonLabel()); ?></span>
	</button>
</div>
<script type="text/javascript">
//<![CDATA[
var XFabricExtensionRegistration = Class.create();
XFabricExtensionRegistration.prototype = {
    initialize: function() {
        this.redirectURL = '<?php echo $this->getUrl($this->getButtonUrl())?>';
        this.buttonId = '<?php echo $this->getHtmlId() ?>';
        this.popupWindow = null;

        $(this.buttonId).observe('click', this.openWindow.bindAsEventListener(this));
    },

    openWindow: function() {
        if (this.popupWindow == null || this.popupWindow.closed) {
            this.popupWindow = window.open(this.redirectURL, 'ExtensionRegistartion', 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=815, height=640');
						}
        else {
            this.popupWindow.focus();
        }
        if (typeof this.intervalID == "number") {
            window.clearInterval(this.intervalID);
            delete this.intervalID;
        }
        this.intervalID = window.setInterval(function(){this.checkWindow();}.bind(this), 500);
        return false;
    },

    checkWindow: function() {
        if (this.popupWindow != null && this.popupWindow.closed) {
            window.clearInterval(this.intervalID);
            delete this.intervalID;
            window.location.reload(true);
        }
    }
};
var registrationExtension = new XFabricExtensionRegistration();
//]]>
</script>
