<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 True Action Network (http://www.trueaction.com)
 */
?>
<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8" />
	<title><?php echo $this->__('Please wait') ?></title>
</head>
<body>
<?php /** @var $_helper Xcom_Ebay_Helper_Data */ ?>
<?php $_helper = $this->helper('fetchback/xfabric'); ?>
<form id="xcom_registration" action="<?php echo $_helper->getRegistrationRequestUrl() ?>" method="post" enctype="multipart/form-data">
<input type="hidden" name="onboarding_info" value="<?php echo $_helper->getRegistrationRequest()->getOnboardingInfo() ?>" />
</form>
<script type="text/javascript">
document.forms['xcom_registration'].submit();
</script>
</body>
</html>